### ISSUE TITLE
Explicitly Export Types

### ISSUE THREAD

**Issue by ocdkerosine** [E-wave112/fincra-node-sdk#51]
i'm having to redefine these types locally which i wouldnt like to maintain. please kindly export the types. great work!

![fincra-dto-error](https://github.com/E-wave112/fincra-node-sdk/assets/81504104/4aad129a-d523-4905-a8a6-b67f1fcfd1ae)

![fincra-no-exported-member](https://github.com/E-wave112/fincra-node-sdk/assets/81504104/49f32f21-50cd-4c92-98be-ccab1c02615c)

**Comment by E-wave112** [comment]
Hello @ocdkerosine  👋 

Thanks for bringing this to my attention 

I am planning on looking through the SDK this week and fixing all possible bugs.

Thanks again!

**Comment by E-wave112** [comment]
This issue has been resolved @ocdkerosine, you can try reinstalling the package and confirm that you can now import DTOs so i can close this issue

Thanks!

**Comment by codedhola** [comment]
This issue can now be closed

**Comment by E-wave112** [comment]
Agreed! cc @ocdkerosine
